### ISSUE TITLE
Add Digilent ZedBoard support

### ISSUE THREAD

**Issue by ieffuie4** [hominoids/SBC_Model_Framework#17]
Would be great to have for https://github.com/hominoids/SBC_Case_Builder this board supported. Its not sold on huge masses and it would fit exactly the use case of the flexibility of the SBC Case Builder. 
Why: Because there are add-on boards that extends the PCB length and those add-on boards are connected with a connector you do not want to connect and disconnect often or even at all when possible.

At the moment there is one single SBC case available on the internet for this SBC: https://makerworld.com/en/models/156181
But this do not fit my need of protecting a connected PCB to it from breaking off when moving the setup.
My exact use case is to protect this combination: https://www.ebay.com/itm/375057574550
You see the price for the reason why i am really interested protecting such a setup with a case.
I do not have laser cutter to cut acrylic to reproduce myself the ebay listing. I have a 3d printer and enough PLA to print the max possible length supported at my printer to cover as much as possible from the attached PCB.

3D models of the zedbord look to exist like written here: https://forum.digilent.com/topic/23549-3-d-step-files/#comment-69095 

Could you add this board to the supported boards so that i could print a case for it in near future to protect this setup as soon as possible?

**Comment by hominoids** [comment]
The short answer is no, I can not add the ZedBoard without having one because there isn't enough detail in the STEP model for it to be useful, other then the PCB size and holes.  It's a complex and very populated PCB and the STEP file only has blocks that represent components.

I will offer a short piece of OpenSCAD code that can produce a top and bottom piece to use with standoffs for a ZedBoard and add-on PCB. The ZedBoard is green but for the optional yellow add-on PCB, you'll need to change the PCB size and position, as well as the hole location so it represent yours.  

![zed_outline](https://github.com/hominoids/SBC_Model_Framework/assets/37256300/59658d23-209c-49d2-9709-414dc525e122)

The code is easy, you'll figure it out. Then compile and export it as an STL to slice and print.  Add some standoffs and feet and it'll protect your rig until you find something better.  IMO, for a development board with IO on all sides of the PCB, your better off with a stacked open sided case then an enclosed case.

Here is a zip file with the OpenSCAD code and the ZedBoard Model it uses.
  
[zedboard_outline.zip](https://github.com/user-attachments/files/16117845/zedboard_outline.zip)
