### ISSUE TITLE
Add new SBC Orange Pi 5

### ISSUE THREAD

**Issue by saulgodino** [hominoids/SBC_Model_Framework#7]
Can you add Orange Pi 5?

**Comment by hominoids** [comment]
I just searched their web site and didn't find any drawings and I don't have a Orange Pi 5.  Do you have drawings? Do you own a Orange Pi 5 and a 3D printer?

**Comment by saulgodino** [comment]
Hello.  This SBC is just released and I'm waiting for mine to be delivered.  There is still no modeled case for it and unfortunately there is no technical drawing showing the measurements.  We only have the measurement of the board (62mm x 100mm) and photos of the board showing the components.  Do you think you can create the model with that?  Yes I have a 3D printer.

**Comment by hominoids** [comment]
If your willing to help once your SBC arrives then it can be done and I'm willing to help you.  What we will need is the measurements to each major component as described at the top of the file sbc_models.cfg in the following orientation.
![pi-5-top-view](https://user-images.githubusercontent.com/37256300/207091833-9b6f392f-4091-4ba6-b14f-d7913b60a0c6.png)

This needs to include all the pcb holes to the center and the following from the lower or upper left corner depending on the PCB side: SDCard, Button, SOC,  GPIO, UART header, USB2/USB3 stack, RJ45, USB2, mipi-csi, mipi-dsi, USCB-C, HDMI, M.2 PCIe.  Once I have that I can create a model and then you will need to do a test print of a case from SBC_Case Builder in order to validate the accuracy of the model.  Let me know if your willing to help, and if so, the measurements when your SBC arrives.

**Comment by saulgodino** [comment]
Hi!  Yes, I'm willing to help.  As soon as my OPI5 arrives, I will take the measurements and inform you here.  Thanks a lot for your attention.

**Comment by alexeyatbluescape** [comment]
@hominoids I have measured everything on my device and created this mock: https://www.printables.com/model/360326-orange-pi-5-3d-model-mock

hope this help. I'm really impressed with this project, its all new to me :)

**Comment by hominoids** [comment]
Unfortunately I have no good way to get measurements from these models.

**Comment by alexeyatbluescape** [comment]
https://3dviewer.net/
![Screenshot 2023-01-06 at 1 33 53 PM](https://user-images.githubusercontent.com/79166410/211076498-d61e074d-0aed-45f2-bad3-8635d15a18b0.png)

load step file there and measure around using ruler tool.

Fusion 360 free license is the best though, though you can see all shapes and inspect all distances.

**Comment by alexeyatbluescape** [comment]
I want to learn the framework thou. and can try a PR, but not in the next month thou.

**Comment by hominoids** [comment]
I'm busy working on version 2 which will add more features and component control, it may be done by that time.  I'll rewrite SBC Case Builder to take advantage of the new format afterwards.  More SBC will be added as time allows but PR's or raw SBC data are welcome anytime.  Instructions on how to do SBC measurements for this framework are located at the top of sbc_models.cfg

**Comment by alexeyatbluescape** [comment]
Using my model started playing with defining the case. It looks pretty simple!
thou need to learn how to add new component types - struggling to find the small camera and LCD connectors for the board.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/79166410/220242870-7668c298-1320-4956-9d85-00c5c24bda93.png">

**Comment by hominoids** [comment]
It looks good so far.  Right now there are only two FPC connector types and they under the "video " class called "mipi_csi" and "mipi_dsi".  More sizes are being worked on for version 2.  If you can get by using the existing ones then the correct ones can be substituted later when version 2 is released.  FYI, they are not that critical since they don't create any openings in SBC Case Builder.  If you want to design some yourself your free to do that and issue a PR too.

**Comment by alexeyatbluescape** [comment]
@hominoids created PR: https://github.com/hominoids/SBC_Model_Framework/pull/11

**Comment by hominoids** [comment]
I merged your PR and will update SBC Case Builder ASAP.
